<?php

/**
 * Aria S.p.A.
 * OPEN 2.0
 *
 *
 * @package    open20\amos\cwh
 * @category   CategoryName
 */

namespace open20\amos\cwh\assets;

use yii\web\AssetBundle;

class CwhAsset extends AssetBundle
{
    public $sourcePath = '@vendor/open20/amos-cwh/src/assets/web';

    public $css = [
        'less/cwh.less'
    ];

    public $depends = [
    ];

    /*
    //force reset cache asset (devel ONLY)
    public $publishOptions = [
        'forceCopy'=>true,
    ];
    */

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }
}
