<?php

/**
 * Aria S.p.A.
 * OPEN 2.0
 *
 *
 * @package    open20\amos\cwh
 * @category   CategoryName
 */

namespace open20\amos\cwh\assets;

use yii\web\AssetBundle;

class ModuleAttivitaAsset extends AssetBundle
{
    public $sourcePath = '@vendor/open20/amos-cwh/src/assets/web';

    public $css = [
    ];
    public $js = [
        'js/aree-interesse.js'
    ];
    public $depends = [
    ];

    /*
    //force reset cache asset (devel ONLY)
    public $publishOptions = [
        'forceCopy'=>true,
    ];
    */

    public function init()
    {
        $moduleL = \Yii::$app->getModule('layout');
        if (!empty($moduleL)) {
            $this->depends [] = 'open20\amos\layout\assets\BaseAsset';
        } else {
            $this->depends [] = 'open20\amos\core\views\assets\AmosCoreAsset';
        }
        $moduleTag = \Yii::$app->getModule('tag');
        if(!empty($moduleTag)){
            $this->depends [] = 'open20\amos\tag\assets\ModuleTagFormAsset';
        }
        parent::init(); // TODO: Change the autogenerated stub
    }
}
